<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-FUGQNF4" ignored="3" name="Default test(failed)" tests="1" failures="1" timestamp="27 Jan 2023 03:25:38 GMT" time="0.046" errors="0">
  <testcase name="test3" time="0.0" classname="org.rerun.A">
    <failure type="java.lang.AssertionError" message="expected [accepted] but found [boundry]">
      <![CDATA[java.lang.AssertionError: expected [accepted] but found [boundry]
at org.rerun.A.test3(A.java:33)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test1" time="0.0" classname="org.rerun.A">
    <ignored/>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.0" classname="org.rerun.A">
    <ignored/>
  </testcase> <!-- test2 -->
  <testcase name="test4" time="0.0" classname="org.rerun.A">
    <ignored/>
  </testcase> <!-- test4 -->
</testsuite> <!-- Default test(failed) -->
